### ISSUE TITLE
FR Create and move to folder

### ISSUE THREAD

**Issue by brimwats** [MrAnyx/obsidian-note-batcher#2]
I would like to move files to a folder when they are created. ideally this plugin would offer a modall using the obsidian API to get folders, here's my current for for this, ideally it could use templater templates 

<%*
const linkUnderCursor = tp.user.linkUnderCursor()
new Notice(linkUnderCursor);
const folders = this.app.vault.getAllLoadedFiles().filter(i => i.children).map(folder => folder.path);
const folderChoicePath = await tp.system.suggester(folders, folders);
const folder = app.vault.getAbstractFileByPath(folderChoicePath);
console.log(folderChoicePath);
const templateType = await tp.system.suggester(["ğ¬Action", "ğAnnotation", "ğAssignment", "ğ¦Audiovisual", "ğBook", "ğBookmark", "âClaim", "ğCoursePart", "ğ»Code", "ğï¸Collection", "ğ¬Conversation", "ğ©ğ»âğ« Course", "ğ¢Dataset", "ğ DefinedTermSet", "ğ¤Definition", "âHowTo", "ğºï¸Map", "ğ¥Meeting", "ğ§Message", "ğ§®Meta", "ğï¸Note", "ğï¸Organization", "ğ¤Person",  "ğPlace", "ğ£Presentation", "ğ§°Product", "âï¸Program", "ğProject", "ğ°Publication", "ğª§Quotation", "ğScholarly Article", "ğ²Scholarship", "ğ­Theory", "ğThesis", "ğ Topic", "ğ¼ï¸Visual Artwork"],["Action & Method Template Template", "Annotation Template", "Assignment Template", "Audiovisual Template", "Book Template", "Bookmark Template", "Claim Template", "Class Note Template", "Code Template", "Collection Template", "Conversation Template", "Course Template", "Dataset Template", "DefinedTermSet Template", "Definition Template", "HowTo Template", "Map Template", "Meeting Template", "Message Template", "Meta Template", "Basic Note Template", "Organization Template", "Person Template", "Place Template", "Presentation Template", "Product Template", "Program Template", "Project Template", "Publication Template", "Quotation Template", "Scholarly Article Template", "Scholarship Template", "Theory Template", "Thesis Template", "Topic Template", "Visual Artwork Template"]);
console.log(folder); const templateTFile = tp.file.find_tfile(templateType); await tp.file.create_new(templateTFile,linkUnderCursor,false,folder).basename
%>

**Comment by brimwats** [comment]
I've also used this for "same folder"

<%*
const linkUnderCursor = tp.user.linkUnderCursor()
new Notice(linkUnderCursor);
const folder = app.vault.getAbstractFileByPath(tp.file.folder)
const templateType = await tp.system.suggester(["ğ¬Action", "ğAnnotation", "ğAssignment", "ğ¦Audiovisual", "ğBook", "ğBookmark", "âClaim", "ğCoursePart", "ğ»Code", "ğï¸Collection", "ğ¬Conversation", "ğ©ğ»âğ« Course", "ğ¢Dataset", "ğ DefinedTermSet", "ğ¤Definition", "âHowTo", "ğºï¸Map", "ğ¥Meeting", "ğ§Message", "ğ§®Meta", "ğï¸Note", "ğï¸Organization", "ğ¤Person", "ğPlace", "ğ£Presentation", "ğ§°Product", "âï¸Program", "ğProject", "ğ°Publication", "ğª§Quotation", "ğScholarly Article", "ğ²Scholarship", "ğ­Theory", "ğThesis", "ğ Topic", "ğ¼ï¸Visual Artwork"],["Action & Method Template Template", "Annotation Template", "Assignment Template", "Audiovisual Template", "Book Template", "Bookmark Template", "Claim Template", "Class Note Template", "Code Template", "Collection Template", "Conversation Template", "Course Template", "Dataset Template", "DefinedTermSet Template", "Definition Template", "HowTo Template", "Map Template", "Meeting Template", "Message Template", "Meta Template", "Basic Note Template", "Organization Template", "Person Template", "Place Template", "Presentation Template", "Product Template", "Program Template", "Project Template", "Publication Template", "Quotation Template", "Scholarly Article Template", "Scholarship Template", "Theory Template", "Thesis Template", "Topic Template", "Visual Artwork Template"]);
const templateTFile = tp.file.find_tfile(templateType);
await tp.file.create_new(templateTFile,linkUnderCursor,false,folder).basename
%>

**Comment by MrAnyx** [comment]
Thanks for your feedback. You can already select the folder you want your notes to be in the settings window in the `Note Batcher` section.

![image](https://github.com/MrAnyx/obsidian-note-batcher/assets/44176707/278a93be-b8f5-49d8-95b1-6b1c7b8fbbd8)

**Comment by brimwats** [comment]
close per #1
